# Generated by Django 3.2.21 on 2023-09-15 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("publisher", "0003_alter_articleevent_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewedPreprint",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manuscript_id", models.BigIntegerField(unique=True)),
                ("content", models.TextField(help_text="valid reviewed-preprint JSON")),
                (
                    "datetime_record_created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time this record was created",
                    ),
                ),
                (
                    "datetime_record_updated",
                    models.DateTimeField(
                        auto_now=True, help_text="Date and time this record was updated"
                    ),
                ),
            ],
            options={
                "ordering": ("manuscript_id",),
            },
        ),
        migrations.CreateModel(
            name="ArticleVersionReviewedPreprintRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articleversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.articleversion",
                    ),
                ),
                (
                    "reviewedpreprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.reviewedpreprint",
                    ),
                ),
            ],
            options={
                "unique_together": {("articleversion", "reviewedpreprint")},
            },
        ),
    ]
