# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("publisher", "0004_auto_20170323_2350")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="ejp_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RA", "Research article"),
                    ("SR", "Short report"),
                    ("AV", "Research advance"),
                    ("RR", "Registered report"),
                    ("TR", "Tools and resources"),
                    ("RE", "Research exchange"),
                    ("SC", "Scientific Correspondence"),
                    ("RS", "Replication Study"),
                ],
                help_text="article as exported from EJP submission system",
                max_length=3,
                null=True,
            ),
        )
    ]
