# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0006_auto_20170531_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleevent',
            name='event',
            field=models.CharField(choices=[('date-ejp-qc', 'date EJP quality check'), ('date-ejp-decision', 'date EJP decision'), ('date-xml-received', 'date received (XML)'), ('date-xml-accepted', 'date accepted (XML)'), ('datetime-action-ingest', "'ingest' event"), ('datetime-action-publish', "'publish' event")], max_length=25),
        ),
    ]
