# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 05:27
from __future__ import unicode_literals

from django.db import migrations, models
from publisher import fragment_logic

def generate_ajson_hashes(apps, schema_editor):
    ArticleVersion = apps.get_model('publisher', 'ArticleVersion')
    for av in ArticleVersion.objects.all():
        merge_result = fragment_logic.merge_and_preprocess(av)
        newhash = fragment_logic.hash_ajson(merge_result)
        av.article_json_hash = newhash
        av.save()

class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0007_auto_20170721_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleversion',
            name='article_json_hash',
            field=models.CharField(default='temp', help_text='md5 digest of merged result. see `fragment_logic.hash_ajson` for algorithm', max_length=32),
            preserve_default=False,
        ),

        migrations.RunPython(generate_ajson_hashes),
    ]
