# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-10 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_articleversion_article_json_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.ForeignKey(help_text="A publisher may have many journals. A journal doesn't necessarily need a Publisher.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='publisher.Publisher'),
        ),
    ]
