# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0008_articleversion_article_json_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlefragment',
            name='datetime_record_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
