# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 17:50


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publisher", "0008_articlecorrection")]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="inception",
            field=models.DateTimeField(
                blank=True, help_text=b"Date journal was created.", null=True
            ),
        )
    ]
