# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 16:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publisher", "0009_journal_inception")]

    operations = [
        migrations.CreateModel(
            name="ArticleVersion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text=b"The title of the article",
                        max_length=255,
                        null=True,
                    ),
                ),
                # needed temporarily to tie an ArticleVersion to an Article in next migration
                (
                    "doi",
                    models.CharField(
                        help_text=b"Article's unique ID in the wider world. All articles must have one as an absolute minimum",
                        max_length=255,
                    ),
                ),
                (
                    "version",
                    models.PositiveSmallIntegerField(
                        default=None,
                        help_text=b"The version of the article. Version=None means pre-publication",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[(b"poa", b"POA"), (b"vor", b"VOR")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "datetime_published",
                    models.DateTimeField(
                        blank=True,
                        help_text=b"Date article first appeared on website",
                        null=True,
                    ),
                ),
                (
                    "datetime_record_created",
                    models.DateTimeField(
                        auto_now_add=True, help_text=b"Date this article was created"
                    ),
                ),
                (
                    "datetime_record_updated",
                    models.DateTimeField(
                        auto_now=True, help_text=b"Date this article was updated"
                    ),
                ),
            ],
        )
    ]
