# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 10:21


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("publisher", "0014_auto_20160411_1145")]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"ordering": ("-date_initial_qc",)}
        )
    ]
