# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 14:54


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("publisher", "0020_auto_20160908_1806")]

    operations = [
        migrations.RemoveField(
            model_name="articleversion", name="article_json_v1_valid"
        ),
        migrations.AddField(
            model_name="articleversion",
            name="article_json_v1_snippet",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                help_text=b"Valid v1 article-json for this article version.",
                null=True,
            ),
        ),
    ]
