# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 10:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0021_auto_20160913_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleversion',
            name='article_json_v1',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'Valid article-json.', null=True),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article_json_v1_raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'raw input article json we receive from different places', null=True),
        ),
        migrations.AlterField(
            model_name='articleversion',
            name='article_json_v1_snippet',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text=b'Valid article-json snippet.', null=True),
        ),
    ]
