# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0023_auto_20160926_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='articleattribute',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='articleattribute',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articleattribute',
            name='key',
        ),
        migrations.DeleteModel(
            name='ArticleAttribute',
        ),
        migrations.DeleteModel(
            name='AttributeType',
        ),
    ]
