# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 13:48


from django.db import migrations, models
import django.db.models.deletion
import publisher.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0025_auto_20161011_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFragment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragment', publisher.fields.JSONField(help_text=b'partial piece of article data to be merged in')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publisher.Article')),
            ],
        ),
    ]
