# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 16:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0027_auto_20161011_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleversion',
            name='article_json_v1_snippet',
        ),
        migrations.AddField(
            model_name='articlefragment',
            name='datetime_record_created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articlefragment',
            name='version',
            field=models.PositiveSmallIntegerField(help_text=b'does the fragment apply to all articles or a specific version?', null=True),
        ),
        migrations.AlterField(
            model_name='articlefragment',
            name='type',
            field=models.CharField(help_text=b'the type of fragment, eg "xml", "content-header", etc', max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='articlefragment',
            unique_together=set([('article', 'type', 'version')]),
        ),
    ]
