# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-09 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0030_auto_20161216_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleversion',
            options={'ordering': ('version',)},
        ),
    ]
