# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-10 14:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("publisher", "0031_auto_20170109_1514")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="manuscript_id",
            field=models.BigIntegerField(
                help_text=b"article identifier from beginning of submission process right through to end of publication.",
                unique=True,
            ),
        )
    ]
