# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-15 13:43
from __future__ import unicode_literals

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("publisher", "0032_auto_20170110_1414")]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="datetime_record_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date this article was created"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="datetime_record_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Date this article was updated"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="doi",
            field=models.CharField(
                help_text="Article's unique ID in the wider world. All articles must have one as an absolute minimum",
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="ejp_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RA", "Research article"),
                    ("SR", "Short report"),
                    ("AV", "Research advance"),
                    ("RR", "Registered report"),
                    ("TR", "Tools and resources"),
                ],
                help_text="article as exported from EJP submission system",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="initial_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="manuscript_id",
            field=models.BigIntegerField(
                help_text="article identifier from beginning of submission process right through to end of publication.",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="rev1_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="rev2_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="rev3_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="rev4_decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RJI", "Reject Initial Submission"),
                    ("RJF", "Reject Full Submission"),
                    ("RVF", "Revise Full Submission"),
                    ("AF", "Accept Full Submission"),
                    ("EF", "Encourage Full Submission"),
                    ("SW", "Simple Withdraw"),
                ],
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="type",
            field=models.CharField(
                blank=True, help_text="xml article-type.", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="articlefragment",
            name="article",
            field=models.ForeignKey(
                help_text="all fragments belong to an article, only some fragments belong to an article version",
                on_delete=django.db.models.deletion.CASCADE,
                to="publisher.Article",
            ),
        ),
        migrations.AlterField(
            model_name="articlefragment",
            name="fragment",
            field=annoying.fields.JSONField(
                help_text="partial piece of article data to be merged in"
            ),
        ),
        migrations.AlterField(
            model_name="articlefragment",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="position in the merge order with lower fragments merged first",
            ),
        ),
        migrations.AlterField(
            model_name="articlefragment",
            name="type",
            field=models.CharField(
                help_text='the type of fragment, eg "xml", "content-header", etc',
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="articlefragment",
            name="version",
            field=models.PositiveSmallIntegerField(
                help_text="if null, fragment applies only to a specific version of article",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="article_json_v1",
            field=annoying.fields.JSONField(
                blank=True, help_text="Valid article-json.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="article_json_v1_snippet",
            field=annoying.fields.JSONField(
                blank=True,
                help_text="Valid article-json snippet, extracted from the valid article-json",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="datetime_published",
            field=models.DateTimeField(
                blank=True,
                help_text="Date article first appeared on website",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="datetime_record_created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Date this article was created"
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="datetime_record_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Date this article was updated"
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("poa", "POA"), ("vor", "VOR")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The title of the article",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="articleversion",
            name="version",
            field=models.PositiveSmallIntegerField(
                default=None,
                help_text="The version of the article. Version=None means pre-publication",
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="inception",
            field=models.DateTimeField(
                blank=True, help_text="Date journal was created.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="name",
            field=models.CharField(
                help_text="Name of the journal.", max_length=255, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="journal",
            name="publisher",
            field=models.ForeignKey(
                help_text="A publisher may have many journals. A journal doesn't necessarily need a Publisher.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="publisher.Publisher",
            ),
        ),
    ]
