# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-20 07:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("publisher", "0033_auto_20170115_1343")]

    operations = [
        migrations.CreateModel(
            name="ArticleVersionRelation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articleversion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.ArticleVersion",
                    ),
                ),
                (
                    "related_to",
                    models.ForeignKey(
                        help_text="the Article this ArticleVersion is related to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publisher.Article",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="articleversionrelation",
            unique_together=set([("articleversion", "related_to")]),
        ),
    ]
