# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0036_auto_20170221_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ejp_type',
            field=models.CharField(blank=True, choices=[('RA', 'Research article'), ('SR', 'Short report'), ('AV', 'Research advance'), ('RR', 'Registered report'), ('TR', 'Tools and resources'), ('RE', 'Unknown')], help_text='article as exported from EJP submission system', max_length=3, null=True),
        ),
    ]
