# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publisher', '0039_auto_20170303_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlefragment',
            options={'ordering': ('position', 'datetime_record_created')},
        ),
    ]
